### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by LuongNguyen0906** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.it-it#1]
Source: 
AAre you a MCT? - Have a look at our GitHub User Guide for MCTs
Need to manually build the lab instructions? - Instructions are available in the MicrosoftLearning/Docker-Build
repository

Current Translation:
Si è un Microsoft Certified Trainer? - Esaminare la guida per utenti di GitHub per Microsoft Certified Trainer
È necessario compilare manualmente le istruzioni del lab? - Le istruzioni sono disponibili nel repository
MicrosoftLearning/Docker-Build

Suggested Translation:
'Si è un Microsoft Certified Trainer? Esaminare la guida per utenti di GitHub per Microsoft Certified Trainer
È necessario compilare manualmente le istruzioni del lab? Le istruzioni sono disponibili nel repository
MicrosoftLearning/Docker-Build

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/184274151-4d687923-38f4-4e05-8d58-a67b0b4b6f9a.png)
