### ISSUE TITLE
readme.md.pdf

### ISSUE THREAD

**Issue by LuongNguyen0906** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.it-it#2]
Source: 
You can submit bugs, changes, improvement and ideas. Find a new Power BI feature before we have? Submit a
new demo!

Current Translation:
È possibile inviare segnalazioni di bug, modifiche, miglioramenti e idee. Se si scopre in anteprima una nuova
funzionalità di Power BI, Inviare una nuova demo.

Suggested Translation:
È possibile inviare segnalazioni di bug, modifiche, miglioramenti e idee. Se si scopre in anteprima una nuova
funzionalità di Power BI, inviare una nuova demo.

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/184070380-156707c8-4581-4985-8048-49a66b2b3aea.png)
