### ISSUE TITLE
Trancation in image/Overlapped text in images/

### ISSUE THREAD

**Issue by LuongNguyen0906** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.it-it#4]
Inconsistent font size in images/Overlagging text in image/Trancation in image/Overlapped text in images/Unloc images (by design???)/Image partially localized

**Comment by stonezy123** [comment]
Now, the image shows it.
![image](https://user-images.githubusercontent.com/49666210/183854895-565208f9-727f-4a1b-a2f5-e555c5053b4a.png)
