### ISSUE TITLE
Just this UI has ENG (ITA) approach. Global issue.

### ISSUE THREAD

**Issue by LuongNguyen0906** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.it-it#8]
Source: 
Click Save.

Current Translation:
Fare clic su Save (Salva).

Suggested Translation:
Fare clic su Salva.

**Comment by stonezy123** [comment]
05-create-dax-calculations-in-power-bi-desktop-advanced.md
07-design-report-in-power-bi-desktop-enhanced.md
10-row-level-security.md
08-create-power-bi-dashboard.md
02-load-data-with-power-query-in-power-bi-desktop.md
06-design-report-in-power-bi-desktop.md
04-create-dax-calculations-in-power-bi-desktop.md
03-configure-data-model-in-power-bi-desktop.md
01-prepare-data-with-power-query-in-power-bi-desktop.md

Run bugfix tool and waiting for result.

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/184070312-f9b3b625-a327-4ddd-acf7-e063052ac474.png)
