### ISSUE TITLE
Inconsistency: UI in text vs UI in image

### ISSUE THREAD

**Issue by LuongNguyen0906** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.it-it#9]
Source: 
Browse Reports

Current Translation:
Esplora report
AND
Sfoglia report

Suggested Translation:
Sfoglia report

**Comment by stonezy123** [comment]
Please help provide the file url.

**Comment by stonezy123** [comment]
02-load-data-with-power-query-in-power-bi-desktop.md
06-design-report-in-power-bi-desktop.md
04-create-dax-calculations-in-power-bi-desktop.md
05-create-dax-calculations-in-power-bi-desktop-advanced.md
07-design-report-in-power-bi-desktop-enhanced.md
10-row-level-security.md
08-create-power-bi-dashboard.md

run the bugfix tool and waiting for result.

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/184070237-5f6bd87c-d4be-4707-93e3-631275a26ab1.png)
